# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
data = {
    "Product": ["A", "B", "C", "A", "B", "C", "A", "B", "C"],
    "Region": ["North", "South", "East", "West", "North", "South", "East", "West", "North"],
    "Units_Sold": [10, 15, 20, 5, 10, 15, 10, 5, 15],
    "Price": [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)

df_sales
df_sales["Revenue"] = df_sales["Units_Sold"] * df_sales["Price"]

df_sales
total_units_sold = df_sales["Units_Sold"].sum()
total_revenue = df_sales["Revenue"].sum()

print(total_units_sold)
print(total_revenue)
average_units_sold = df_sales["Units_Sold"].mean()
average_revenue = df_sales["Revenue"].mean()

print(average_units_sold)
print(average_revenue)

105
16000
11.666666666666666
1777.7777777777778

## Grouping Data

In [3]:
df_sales.groupby("Product")[["Units_Sold", "Revenue"]].sum()
df_sales.groupby("Region")[["Units_Sold", "Revenue"]].mean()
df_sales.groupby(["Product", "Region"])[["Units_Sold", "Revenue"]].sum()

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [4]:
df_sales.sort_values(by="Units_Sold", ascending=True)
df_sales.sort_values(by="Revenue", ascending=False)
df_sales["Revenue_Rank"] = df_sales["Revenue"].rank(ascending=False)

df_sales
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [5]:
product_data = {
    "Product": ["A", "B", "C"],
    "Category": ["Electronics", "Furniture", "Appliances"]
}

df_products = pd.DataFrame(product_data)

df_products
df_merged = pd.merge(df_sales, df_products, on="Product")

df_merged
df_merged
df_merged.groupby("Category")["Revenue"].sum()

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64